//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int fpsText = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int numThreadEntry = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int parallelBtn = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int showBtn = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int startStopBtn = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int viewLayout = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
